# thor/Dockerfile.dev
FROM python:3.11-slim

ENV PYTHONFAULTHANDLER=1 \
    PYTHONHASHSEED=random \
    PYTHONUNBUFFERED=1 \
    PIP_DEFAULT_TIMEOUT=100 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1 \
    POETRY_VERSION=2.1.3

WORKDIR /app

# Install poetry
RUN pip install "poetry==$POETRY_VERSION"

# Copy dependency definition files
COPY pyproject.toml poetry.lock README.md ./

COPY . .

RUN poetry config virtualenvs.create false && \
    poetry install

ENTRYPOINT ["thor"]
