name: Build on release

on:
  release:
    types: [published]
    branches:
      - 'main'
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    name: 'Build & Push ${{ matrix.service }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [thor, loki, bifrost, heimdall, hermod]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      
      - name: Log in to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ env.GITHUB_TOKEN }}

      - name: Docker meta for ${{ matrix.service }}
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}/${{ matrix.service }}
          tags: |
            type=semver,pattern={{version}}
            type=sha
      
      - name: 'Build and push ${{ matrix.service }}'
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
